# Change these first
owner: arturodc37 # Your GitHub organization or username, where this repository lives
repo: Service-Status-Check # The name of this repository

sites:
  - name: Avangenio
    url: https://avangenio.com
  - name: Cujae
    url: https://cujae.edu.cu
  - name: Correo
    url: correo.avangenio.com
    port: 25
    check: "tcp-ping"
    ipv6: false

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /Service-Status-Check
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "Online Status of:"
  navbar:
    - title: Status
      href: /Service-Status-Check
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
